-- AlterEnum
ALTER TYPE "Taille" ADD VALUE 'UNIQUE';

-- AlterTable
ALTER TABLE "Produit" ADD COLUMN     "categorie" TEXT NOT NULL DEFAULT 'Vêtements',
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "estNouveau" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stock" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
